Feature add dice cls
crimson206/MonopolyWithCSharp pull request #10
Opened 2022-09-21 19:33 UTC by crimson206

This pull request is to add IDice interface and allow player to roll dice

To achieve the goal
- add interface IDice
- add class RollDiceResult
- add (private) player.RollDice()

2022-09-22 15:16 UTC, dlsl123 requested changes

2022-09-22 15:16 UTC, dlsl123 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Resutls = new int[] { die1, die2 };
typo
```suggestion
        this.Results = new int[] { die1, die2 };
```

2022-09-22 15:16 UTC, dlsl123 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Resutls = new int[] { die1, die2 };
If the results are an array anyway, why isn't the input an array as well?

Right now the output is generic enough to be used with different amounts of dice, but the input is hardcoded to two dice values

2022-09-22 15:16 UTC, dlsl123 commented on src/ClassLibrary/RollDiceResult.cs
> +    public RollDiceResult(int die1, int die2)
since you already have a class called Dice, you probably shouldn't call the arguments `die` if they aren't Dice.
Maybe diceValue(s)?

2022-09-22 15:16 UTC, dlsl123 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Total = die1 + die2;
Do you want to write some tests for this?

2022-09-22 18:18 UTC, crimson206 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Resutls = new int[] { die1, die2 };
Cleared

2022-09-22 18:19 UTC, crimson206 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Resutls = new int[] { die1, die2 };
Cleared

2022-09-22 18:19 UTC, crimson206 commented on src/ClassLibrary/RollDiceResult.cs
> +    public RollDiceResult(int die1, int die2)
Cleared

2022-09-22 18:20 UTC, crimson206 commented on src/ClassLibrary/RollDiceResult.cs
> +        this.Total = die1 + die2;
I wrote two tests.
Let me know please, if there are more things to improve.
Thank you for all feedbacks :)

2022-09-23 07:10 UTC, dlsl123 approved these changes

2022-09-23 12:38 UTC, merged